Question1 

In [2]:
import numpy as np 
arr=np.array([10,20,30,40,50])
print("after adding 2")
print(arr+2)
print("after multiplying")
print(arr*3)
print("after dividing")
print(arr/2)


after adding 2
[12 22 32 42 52]
after multiplying
[ 30  60  90 120 150]
after dividing
[ 5. 10. 15. 20. 25.]


Question 2

In [4]:

arr = np.array([1, 2, 3, 6, 4, 5])

print("Array after reversing:")
print(arr[::-1])


Array after reversing:
[5 4 6 3 2 1]


In [ ]:

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

max_count = np.max(counts)
most_frequent = values[counts == max_count]

print("\nFor x:")
print("Most frequent value(s):", most_frequent)

for value in most_frequent:
    print("Indices of", value, ":", np.where(x == value)[0])


For x:
Most frequent value(s): [1]
Indices of 1 : [0 5 7 8 9]


In [6]:

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = np.max(counts)
most_frequent = values[counts == max_count]

print("\nFor y:")
print("Most frequent value(s):", most_frequent)

for value in most_frequent:
    print("Indices of", value, ":", np.where(y == value)[0])


For y:
Most frequent value(s): [1 3]
Indices of 1 : [0 1 2]
Indices of 3 : [4 8 9]


Question3

In [5]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0,1])

20


In [6]:
print(arr[2, 0])

70


Question 4


In [12]:
Manvi=np.linspace(10,100,25)
print(Manvi)
print("dimensions are",Manvi.ndim)
print("shape",Manvi.shape)
print("total elemnets",Manvi.size)
print("data type",Manvi.dtype)
print("tottal bytes",Manvi.nbytes)
print("Reshaped array:")
print(Manvi.reshape(-1,1))
print("Transpose:")
print(Manvi.reshape(1,25).T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions are 1
shape (25,)
total elemnets 25
data type float64
tottal bytes 200
Reshaped array:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Question5

In [17]:
ucs420_Manvi = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
print(ucs420_Manvi)
print("mean",np.mean(ucs420_Manvi))
print("median",np.median(ucs420_Manvi))
print("Maximum", np.max(ucs420_Manvi))
print("Minimum", np.min(ucs420_Manvi))
print("Unique elements", np.unique(ucs420_Manvi))

reshaped_ucs420_Manvi = ucs420_Manvi.reshape(4, 3)

print("reshaped array",reshaped_ucs420_Manvi)

resized_ucs420_Manvi = np.resize(ucs420_Manvi, (2, 3))

print("resized array",resized_ucs420_Manvi)



[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean 43.333333333333336
median 37.5
Maximum 90
Minimum 10
Unique elements [10 15 20 30 35 40 50 60 70 80 90]
reshaped array [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized array [[10 20 30]
 [40 50 60]]
